instance: "{{ hostvars[inventory_hostname]['instance_no'] }}"
domain: "{{ hostvars[inventory_hostname]['uuid'] }}.demo1.pd.stonedoor.io"
ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
hosts_add_default_ipv4: False
region: us-east-2
vpc_subnet_id: subnet-0c020946935fab135
security_group: lab-systems-private
project: demo1-labenv
