base_domain: "demo1.pd.stonedoor.io"
project: "demo1-labenv"
region: "us-east-2"
vpc_subnet_id: "subnet-0c020946935fab135"
security_groups: "lab-systems-private"
rhel8_client_image: "ami-0e66d4735ab291b3e"
rhel8_idm_server_image: "ami-0791ef89192654dca"
rhel7_sat6_server_image: "ami-064c98f6ca669f230"
