---
# tasks file for rh-infra-lab-ec2

- name: Launch RHEL 8.1 workstation
  ec2:
     key_name: "{{ my_keyname }}"
     group: "{{ security_group }}"
     instance_type: "{{ rh_wks_instance_type }}"
     image: "{{ rh_wks_image }}"
     wait: true
     region: "{{ region }}"
     instance_tags:
       Name: "{{ uuid.stdout }}-rhel8-wks"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: no
  register: ec2
  tags: [ rh_wks ]

- name: Launch RHEL 8.1 IdM server
  ec2:
     key_name: "{{ my_keyname }}"
     group: "{{ security_group }}"
     instance_type: "{{ rh_idm_instance_type }}"
     image: "{{ rh_idm_image }}"
     wait: true
     region: "{{ region }}"
     instance_tags:
       Name: "{{ uuid.stdout }}-rhel8-idm"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: no
  register: ec2
  tags: [ rh_idm ]

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  delegate_to: "{{ item.private_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ ec2.instances }}"
