---
# vars file for rh-sat6-ec2
instance_type: t3.xlarge
security_group: lab-systems-private
image: ami-033ecaafebce8a8bb
count: 1
region: us-east-2
vpc_subnet_id: subnet-0c020946935fab135
my_keyname: "{{ uuid }}-lab-key"
