---
# vars file for deploy-lab-ec2-instance
domain: "{{ uuid }}.{{ base_domain }}"
hostname: "{{ system_type | regex_replace ('_','-') }}-{{ item.ami_launch_index }}"
ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
my_keyname: "{{ uuid }}-lab-key"
user: "{{ lookup('env','USER') }}"
