---
# vars file for deploy-lab-ec2-instance
#instance_type: No default, must set when calling role
#image: No default, must set when calling role
purpose: "Lab virtual machine"
count: 1
region: us-east-2
vpc_subnet_id: subnet-0c020946935fab135
security_group: lab-systems-private
project: demo1-labenv
my_keyname: "{{ uuid }}-lab-key"
