---
# vars file for deploy-lab-ec2-instance
domain: "{{ uuid }}.{{ base_domain }}"
group_launched: "{{ system_type | regex_replace ('-','_') }}_launched"
host_name: "{{ system_type | regex_replace ('_','-') }}-{{ item.ami_launch_index }}"
my_keyname: "{{ uuid }}-lab-key"
user: "{{ lookup('env','USER') }}"
