---
# vars file for deploy-lab-ec2-instance
deploy_date: "{{ ansible_date_time.date }}"
domain: "{{ uuid }}.{{ base_domain }}"
ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
hostname: "{{ system_type | regex_replace ('_','-') }}-{{ item.ami_launch_index }}.{{ domain }}"
my_keyname: "{{ uuid }}-lab-key"
user: "{{ lookup('env','USER') }}"
