---
# tasks file for rh-sat6-ec2
- name: Launch Satellite 6 server
  ec2:
     key_name: "{{ my_keyname }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     count: "{{ count }}"
     wait: true
     region: "{{ region }}"
     instance_tags:
       Name: "{{ uuid.stdout }}-rh-sat6"
       project: demo1-labenv
       labenv: "{{ uuid.stdout }}"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: no
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  delegate_to: "{{ item.private_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ ec2.instances }}"

- name: Update lab environment information file
  lineinfile: 
    path: "/tmp/{{ uuid.stdout }}-lab-environment.txt"
    regexp: "{{ item.private_ip }}"
    line: "Satellite 6 server: {{ item.private_ip }}"
    create: yes
  loop: '{{ec2.instances}}'


