---
# Red Hat Infrastructure for Windows Administrators
- name: Assign UUID to lab deployment
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Generate UUID
      shell: uuidgen | cut -b 1,2,3,4
      register: uuid_output

    - set_fact:
        uuid: "{{ uuid_output.stdout }}"
  tags: always

- name: Provision lab environment on AWS EC2
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Upload SSH public key to AWS EC2
      include_role:
        name: ssh-key-ec2
      tags: always

    - name: Provision RHEL 8 client(s)
      include_role:
        name: deploy-lab-ec2-instance
      vars:
        instance_type: t3.medium
        image: "{{ rhel8_client_image }}"
        purpose: "RHEL 8 client"
        system_type: "rhel8_client"
      tags: rhel8_client

    - name: Provision RHEL 8 IdM server(s)
      include_role:
        name: deploy-lab-ec2-instance
      vars:
        instance_type: t3.medium
        image: "{{ rhel8_idm_server_image }}"
        purpose: "RHEL 8 IdM server"
        system_type: "rhel8_idm_server"
      tags: rhel8_idm_server

    - name: Provision Red Hat Satellite 6 server(s)
      include_role:
        name: deploy-lab-ec2-instance
      vars:
        instance_type: t3.xlarge
        image: "{{ rhel7_sat6_server_image }}"
        purpose: "Red Hat Satellite 6 server"
        system_type: "rhel7_sat6_server"
      tags: rhel7_sat6_server

    - name: Remove SSH public key from AWS EC2
      vars:
        remove_aws_key: True
      include_role:
        name: ssh-key-ec2
      tags: always

- name: Communicate results
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Print lab information
      debug:
        msg: "Your UUID is {{ uuid }}. See /tmp/{{ uuid }}-lab-environment.txt for details regarding your new lab environment."
  tags: always
