---
# Red Hat Infrastructure for Windows Administrators
- name: Assign UUID to lab deployment
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Generate UUID
      shell: uuidgen | cut -b 1,2,3,4
      register: uuid_output

    - set_fact:
        uuid: "{{ uuid_output.stdout }}"
  tags: always

- name: Provision lab environment on AWS EC2
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Upload SSH public key to AWS EC2
      include_role:
        name: ssh-key-ec2
      tags: always

    - name: Provision RHEL 8 client(s)
      include_role:
        name: deploy-lab-ec2-instance
      vars:
        instance_type: t3.medium
        image: ami-0e66d4735ab291b3e
        purpose: "RHEL 8 client"
        system_type: "rhel8_client"
      tags: rhel8_client

    - name: Provision RHEL 8 IdM server(s)
      include_role:
        name: deploy-lab-ec2-instance
      vars:
        instance_type: t3.medium
        image: ami-09d3af229af1d17d2
        purpose: "RHEL 8 IdM server"
        system_type: "rhel8_idm_server"
      tags: rhel8_idm_server

    - name: Provision Red Hat Satellite 6 server(s)
      include_role:
        name: deploy-lab-ec2-instance
      vars:
        instance_type: t3.xlarge
        image: ami-033ecaafebce8a8bb
        purpose: "Red Hat Satellite 6 server"
        system_type: "rhel7_sat6_server"
      tags: rhel7_sat6_server

- name: Configure RHEL 8 client(s)
  hosts: "{{ system_type | regex_replace ('-','_') }}_launched"
  become: True
  gather_facts: True
  vars:
    system_type: "rhel8_client"
  tasks:
    - name: Set hostname
      command: "hostnamectl set-hostname {{ hostname }}"

    - name: Update /etc/hosts
      include_role:
        name: bertvv.hosts
  tags: rhel8_client

- name: Configure RHEL 8 IdM servers(s)
  hosts: "{{ system_type | regex_replace ('-','_') }}_launched"
  become: True
  gather_facts: True
  vars:
    system_type: "rhel8_idm_server"
  tasks:
    - name: Set hostname
      command: "hostnamectl set-hostname {{ hostname }}"

    - name: Update /etc/hosts
      include_role:
        name: bertvv.hosts
  tags: rhel8_idm_server

- name: Configure Red Hat Satellite 6 server(s)
  hosts: "{{ system_type | regex_replace ('-','_') }}_launched"
  become: True
  gather_facts: True
  vars:
    system_type: "rhel7_sat6_server"
  tasks:
    - name: Set hostname
      command: "hostnamectl set-hostname {{ hostname }}"

    - name: Update /etc/hosts
      include_role:
        name: bertvv.hosts
  tags: rhel7_sat6_server

- name: Communicate results
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Print lab information
      debug:
        msg: "Your UUID is {{ uuid }}. See /tmp/{{ uuid }}-lab-environment.txt for details regarding your new lab environment."
  tags: always
