---
- name: Create RHEL 8.1 lab workstation
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Generate UUID
      shell: uuidgen | cut -b 1,2,3,4
      register: uuid

    - name: Create SSH key
      include_role:
        name: ssh-key-ec2
        public: yes

    - name: Provision RHEL 8 workstation
      include_role:
        name: rh-wks-ec2
