---
# Red Hat Infrastructure for Windows Administrators
- name: Assign UUID to lab deployment
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Generate UUID
      shell: uuidgen | cut -b 1,2,3,4
      register: uuid_output

    - set_fact:
        uuid: "{{ uuid_output.stdout }}"
  tags: always

- name: Provision lab environment on AWS EC2
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Upload SSH public key to AWS EC2
      include_role:
        name: ssh-key-ec2
      tags: always

    - name: Provision RHEL 8 client(s)
      include_role:
        name: rh-client-ec2
      tags: rh-client

    - name: Provision RHEL 8 IdM server(s)
      include_role:
        name: rh-idm-ec2
      tags: rh-idm

    - name: Provision Red Hat Satellite 6 server(s)
      include_role:
        name: rh-sat6-ec2
      tags: rh-sat6

- name: Configure RHEL 8 client(s)
  hosts: rh_client_launched
  become: True
  gather_facts: True
  tasks:
    - name: Set hostname
      command: "hostnamectl set-hostname rh-client-{{ instance }}.{{ domain }}"

    - name: Update /etc/hosts
      include_role:
        name: bertvv.hosts
      vars:
        hosts_entries:
          - name: "rh-client-{{ instance }}.{{ domain }}"
            ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  tags: rh-client

- name: Configure RHEL 8 IdM servers(s)
  hosts: rh_idm_launched
  become: True
  gather_facts: True
  tasks:
    - name: Set hostname
      command: hostnamectl set-hostname rh-client-{{ instance }}.{{ domain }}

    - name: Update /etc/hosts
      include_role:
        name: bertvv.hosts
      vars:
        hosts_entries:
          - name: "rh-client-{{ instance }}.{{ domain }}"
            ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  tags: rh-idm

- name: Configure Red Hat Satellite 6 server(s)
  hosts: rh_sat6_launched
  become: True
  gather_facts: True
  tasks:
    - name: Set hostname
      command: hostnamectl set-hostname rh-client-{{ instance }}.{{ domain }}

    - name: Update /etc/hosts
      include_role:
        name: bertvv.hosts
      vars:
        hosts_entries:
          - name: "rh-client-{{ instance }}.{{ domain }}"
            ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  tags: rh-sat6

- name: Communicate results
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Print lab information
      debug:
        msg: "Your UUID is {{ uuid }}. See /tmp/{{ uuid }}-lab-environment.txt for details regarding your new lab environment."
  tags: always
