---
# Red Hat Infrastructure for Windows Administrators
- name:
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Generate UUID
      shell: uuidgen | cut -b 1,2,3,4
      register: uuid_output

    - set_fact:
        uuid: "{{ uuid_output.stdout }}"

- name: Provision lab environment on AWS EC2
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Upload SSH public key to AWS EC2
      include_role:
        name: ssh-key-ec2

    - name: Provision RHEL 8 client(s)
      include_role:
        name: rh-client-ec2

#    - name: Provision RHEL 8 IdM server(s)
#      include_role:
#        name: rh-idm-ec2

#    - name: Provision Red Hat Satellite 6 server(s)
#      include_role:
#        name: rh-sat6-ec2

- name: Configure RHEL 8 client(s)
  hosts: rh_client_launched
  gather_facts: True
  tasks:
    - name: Set hostname
      include_role:
        name: ahuffman.hosts
      vars:
        hosts_backup: False
        hosts_set_hostname: True
        hosts_hostname:
          hostname: rh-client
          domain: "{{ hostvars['localhost']['uuid'] }}.demo1.pd.stonedoor.io"
          ip_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          alias_loopback: False

- name: Communicate results
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Print lab information
      debug:
        msg: "Your UUID is {{ uuid }}. See /tmp/{{ uuid }}-lab-environment.txt for details regarding your new lab environment."

    - name: Debug output
      debug:
        var: groups
