---
# Update /etc/hosts. Requires root privileges.
- name: Add lab systems to /etc/hosts
  hosts: localhost
  become: True
  gather_facts: False
  tasks:
  - name: Update hosts file to match current lab systems
    blockinfile:
      path: /etc/hosts
      block: "{{ lookup('file', lab_hosts_path) }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - LAB HOSTS" 
