---
# Update /etc/hosts. Requires root privileges.
- name: Add lab systems to /etc/hosts
  hosts: localhost
  become: True
  gather_facts: False
  vars:
    hosts_file: "/etc/hosts"
    lab_hosts_file: "/lab01/rh-infra-lab-hosts"
  tasks:
  - name: Update /etc/hosts
    blockinfile:
      path: "{{ hosts_file }}"
      block: "{{ lookup('file', lab_hosts_file) }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - LAB HOSTS" 
