---
# tasks file for deploy-lab-ec2-instance
- name: Deploy new host on AWS EC2
  block:
  - name: Launch EC2 instance
    ec2:
       key_name: "{{ my_keyname }}"
       group: "{{ security_groups }}"
       instance_type: "{{ instance_type }}"
       image: "{{ image }}"
       count: "{{ count }}"
       wait: true
       region: "{{ region }}"
       instance_tags:
         Name: "{{ uuid }}-{{ system_type }}"
         project: "{{ project }}"
         labenv: "{{ uuid }}"
         user: "{{ user }}"
       vpc_subnet_id: "{{ vpc_subnet_id }}"
       assign_public_ip: no
    register: ec2
  
  - name: Add new instance to host group
    add_host:
      groups:
        - "{{ group_launched }}"
        - launched_ec2_instances
      ami_launch_index: "{{ item.ami_launch_index }}"
      hostname: "{{ item.private_ip }}"
      fqdn: "{{ host_name }}.{{ domain }}"
      id: "{{ item.id }}"
      private_ip: "{{ item.private_ip }}"
      purpose: "{{ purpose }}"
      uuid: "{{ uuid }}"
    loop: "{{ ec2.instances }}"
  when: not create_lab_env_doc
  
- name: Basic host configuration
  block:
  - name: Wait for SSH to come up
    wait_for_connection:
      delay: 60
      timeout: 320
    loop: "{{ ec2.instances }}"
  
  - name: Set hostname on new host
    command: "hostnamectl set-hostname {{ host_name }}.{{ domain }}"
    loop: "{{ ec2.instances }}"
  
  - name: Update /etc/hosts on new host
    lineinfile: 
      path: "/etc/hosts"
      regexp: "{{ item.private_ip }}"
      line: "{{ item.private_ip }} {{ host_name }}.{{ domain }}"
    loop: "{{ ec2.instances }}"
  become: True
  delegate_to: "{{ item.private_dns_name }}"
  when: not create_lab_env_doc
  
- name: Update control node for new hosts
  block:
  - name: Add new hosts to /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: "^{{ hostvars[item]['private_ip'] }}"
      line: "{{ hostvars[item]['private_ip'] }} {{ hostvars[item]['fqdn'] }}"
    loop: "{{ groups[group_launched] }}"
  when: not create_lab_env_doc

- name: Run tasks to document new lab environment
  include_tasks: lab_env_doc.yml
  when: create_lab_env_doc
