---
# defaults file for deploy-lab-ec2-instance
#image: No default, must set when calling role
#region: No default, must set when calling role
#vpc_subnet_id: No default, must set when calling role
#security_groups: No default, must set when calling role
#
create_lab_env_doc: False
#
count: 1
instance_type: "t3.small"
hosts_file: "/lab01/rh-infra-lab-hosts"
project: "my-lab-environment"
purpose: "Lab virtual machine"
system_type: "lab_system"
