---
# tasks file for local-accounts
- name: Create local user (with sudo to root permission)
  become: True
  user:
    append: yes
    groups: "{{ supplementary_groups }}"
    name: "{{ username }}"
    state: present

- name: Setup SSH access using public key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '{{ my_public_key }}') }}" 
