---
# tasks file for local-accounts
- name: Create local user (with sudo to root permission)
  become: True
  user:
    append: yes
    groups: wheel
    name: "{{ lookup('env','USER') }}"
    state: present

- name: Setup SSH access using public key
  authorized_key:
    user: "{{ lookup('env','USER') }}"
    state: present
    key: "{{ lookup('file', '{{ my_keyfile }}.pub') }}" 
