---
# tasks file for config-rhel7-sa6-server 
- name: Update Satellite 6 configuration for deployed hostname
  block:
  - name: Save original hostname
    command: uname -n
    register: orig_hostname

  - name: Temporarily change hostname to baseline value used when building Sat6 image
    command: "hostnamectl set-hostname rhel7-sat6-server-baseline.demo1.pd.stonedoor.io"

  - name: Add Sat6 baseline hostname to /etc/hosts
    lineinfile:
      line: "{{ ip_address }} rhel7-sat6-server-baseline.demo1.pd.stonedoor.io"
      path: /etc/hosts
      state: present

  - name: Run Satellite 6 change hostname command
    shell: |
      satellite-change-hostname {{ orig_hostname.stdout }} -y \
        --username admin \
        --password redhat

  - name: Remove duplicate lines from /etc/hosts file
    command: awk '!a[$0]++' /etc/hosts
  become: True
