---
# tasks file for rh-idm-ec2
- name: Launch RHEL 8 IdM instance
  ec2:
     key_name: "{{ my_keyname }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     count: "{{ count }}"
     wait: true
     region: "{{ region }}"
     instance_tags:
       Name: "{{ uuid }}-rh-idm"
       project: demo1-labenv
       labenv: "{{ uuid }}"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: no
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: rh_idm_launched
    uuid: "{{ uuid }}"
    instance_no: "{{ idx }}"
  loop: "{{ ec2.instances }}"
  loop_control:
    index_var: idx

- name: Wait for SSH to come up
  delegate_to: "{{ item.private_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ ec2.instances }}"

- name: Update lab environment information file
  lineinfile: 
    path: "/tmp/{{ uuid }}-lab-environment.txt"
    regexp: "{{ item.private_ip }}"
    line: "RHEL 8 IdM server - instance {{ instance }}: {{ item.private_ip }}"
    create: yes
  loop: "{{ec2.instances}}"

