---
# tasks file for ssh-key-ec2
- name: Create directory for SSH key
  file:
    path: "{{ lookup('env','HOME') }}/.ssh/"
    state: directory
    mode: '0700'

- name: Generate SSH key for local user
  openssh_keypair:
    path: "{{ my_keyfile }}"

- name: Upload public key to AWS
  ec2_key:
    name: "{{ my_keyname }}"
    key_material: "{{ lookup('file', '{{ my_keyfile }}.pub') }}"
    region: "{{ region }}"

