---
# tasks file for rh-wks-ec2
- name: Launch RHEL 8.1 instance
  ec2:
     key_name: "{{ my_keyname }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     wait: true
     region: "{{ region }}"
     instance_tags:
       Name: "{{ uuid.stdout }}-rhel8-wks"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: no
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  delegate_to: "{{ item.private_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ ec2.instances }}"
